### PR TITLE
Test CI job

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
run jenkins-python-sdk-ut

**Comment by Dhivyaaj** [comment]
run jenkins-python-sdk-ut

**Comment by ArpitAVI** [comment]
run avitools-py-ut

**Comment by ArpitAVI** [comment]
run jenkins-python-sdk-ut

**Comment by chugh007** [comment]
run jenkins-python-sdk-ut

**Pull request closed without merging**
